### ISSUE TITLE
Lógica - Cabecera

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#40]
En esta tarea se incluye la implementación de la lógica de la "Cabecera" 
Esta tarea incluye generar el código necesario para solicitar al backend los datos del usuario activo y mostrar los pertinentes en la cabecera de las pantallas.
También incluye la incorporación del código necesario para realizar un cierre de sesión de la aplicación

**Comment by aroaaredondo** [comment]
Ya se ha realizado la lógica de la cabecera

**Comment by LuciaMoralesRosa** [comment]
Se debe añadir el cierre de sesión

**Comment by titoMar008** [comment]
La cabecera ya ha sido termindad
