### ISSUE TITLE
Diseño - Pantalla partidasIniciadas

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#50]
En esta tarea se incluye el diseño HTML y CSS de la pantalla "partidasIniciadas".
No se incluye la lógica para el correcto funcionamiento de la pantalla ni su navegabilidad ni los test pertinentes.

**Comment by aroaaredondo** [comment]
Se ha creado una nueva pantalla de seleccion entre el juego y el modo de partida para poder selecionar salas ya creadas
