### ISSUE TITLE
Diseño - Pantalla crearSalaPrivada

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#53]
En esta tarea se incluye el diseño HTML y CSS de la pantalla "crearSalaPrivada".
No se incluye la lógica para el correcto funcionamiento de la pantalla ni su navegabilidad ni los test pertinentes.

**Comment by aroaaredondo** [comment]
Se ha realizado el html y css de crear una sala privada y el html y css para observer el código de la sala privada
