### ISSUE TITLE
Lógica - Pantalla crearSalaPrivada

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#54]
En esta tarea se incluye la implementación de la lógica de la pantalla "crearSalaPrivada" 
No se incluye el diseño de la pantalla, la navegabilidad ni los test pertinentes.

**Comment by aroaaredondo** [comment]
se crean salas privadas blackjack quedaria para poker

**Comment by titoMar008** [comment]
ya se ha implementado la posibilidad de crear una sala privada
