### ISSUE TITLE
Diseño - Pantalla nuevaReanudar

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#56]
En esta tarea se incluye el diseño HTML y CSS de la pantalla "nuevaReanudar".
No se incluye la lógica para el correcto funcionamiento de la pantalla ni su navegabilidad ni los test pertinentes.

**Comment by titoMar008** [comment]
ya se ha hecho el diseño de reanudar
