### ISSUE TITLE
Lógica - Pantalla unionSalaPrivada

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#60]
En esta tarea se incluye la implementación de la lógica de la pantalla "unionSalaPrivada" 
No se incluye el diseño de la pantalla, la navegabilidad ni los test pertinentes.

**Comment by aroaaredondo** [comment]
Esta unirse a sala privada de bj pero no de poker

**Comment by titoMar008** [comment]
ya se ha realizado las partidas privadas
