### ISSUE TITLE
Lógica - Pantalla pokerJuego

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#63]
En esta tarea se incluye la implementación de la lógica de la pantalla "pokerJuego" 
No se incluye el diseño de la pantalla, la navegabilidad ni los test pertinentes.

**Comment by LuciaMoralesRosa** [comment]
No hay logica en esta pantalla

**Comment by titoMar008** [comment]
el poker ya ha sido terminado
