### ISSUE TITLE
Diseño - Pantalla reanudacionPartida

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#65]
En esta tarea se incluye el diseño HTML y CSS de la pantalla "reanudacionPartida".
No se incluye la lógica para el correcto funcionamiento de la pantalla ni su navegabilidad ni los test pertinentes.

**Comment by titoMar008** [comment]
ya se ha hecha la pantalla de reanudar partida
