### ISSUE TITLE
Diseño - Pantalla bjJuego

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#68]
En esta tarea se incluye el diseño HTML y CSS de la pantalla "bjJuego".
No se incluye la lógica para el correcto funcionamiento de la pantalla ni su navegabilidad ni los test pertinentes.

**Comment by aroaaredondo** [comment]
Se ha realizado el diseño de la pantalla de juego de one-player

**Comment by aroaaredondo** [comment]
Ultimos retoques de botones que quedaban acabados
