### ISSUE TITLE
Diseño - Pantalla tienda

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#74]
En esta tarea se incluye el diseño HTML y CSS de la pantalla "tienda".
No se incluye la lógica para el correcto funcionamiento de la pantalla ni su navegabilidad ni los test pertinentes.

**Comment by aroaaredondo** [comment]
Diseño del html y css realizado

**Comment by titoMar008** [comment]
la tineda ya se ha realizado
