### ISSUE TITLE
Lógica - Pantalla tienda

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#75]
En esta tarea se incluye la implementación de la lógica de la pantalla "tienda" 
No se incluye el diseño de la pantalla, la navegabilidad ni los test pertinentes.

**Comment by titoMar008** [comment]
Ya se ha realizado la lógica de la pantalla de la tienda. Se nos olvido cerrar este issue antes.
