### ISSUE TITLE
Diseño - Pantalla pokerSelecciónModo

### ISSUE THREAD

**Issue by LuciaMoralesRosa** [UNIZAR-30226-2024-08/front-Web#77]
En esta tarea se incluye el diseño HTML y CSS de la pantalla "pokerSelecciónModo".
No se incluye la lógica para el correcto funcionamiento de la pantalla ni su navegabilidad ni los test pertinentes.

**Comment by aroaaredondo** [comment]
El diseño se ha reallizado
